#!/usr/bin/env python3
import pymongo

client = pymongo.MongoClient("mongodb+srv://admin:LeErz4HubDEX4iHY@cluster0.e2stt.gcp.mongodb.net/teamr?retryWrites=true&w=majority")
db = client.teamr
collection = db.User
collection.delete_many({})

